return {
  -- 'catppuccin/nvim',
  -- name = 'catppuccin',
  -- priority = 1000,
  -- config = function()
  --   require('catppuccin').setup({
  --     integrations = {
  --       cmp = true,
  --       treesitter = true,
  --       mason = true,
  --       noice = true,
  --       which_key = true,
  --       gitsigns = true,
  --       notify = true,
  --       snacks = {
  --         enabled = true,
  --       },
  --     },
  --     flavour = 'mocha',
  --   })
  --   vim.cmd.colorscheme('catppuccin')
  -- end,
}
